### ISSUE TITLE
hard to build using visual studio 2022

### ISSUE THREAD

**Issue by mmj-the-fighter** [andrew-lim/sw3dcpp#1]
I tried to make a build in visual studio community edition 2022. There was a lot of Unicode related errors. And when I corrected them I got a runtime exception when creating the window itself due to read access violation at the following code. 
 if ( self )
   return self->handleMessage(msg, wParam, lParam); 
when the exception was thrown self was not a NULL pointer.

**Comment by andrew-lim** [comment]
I haven't tested it with 64-bit Visual Studio.
But for now try changing this line in Windows.cpp from

    SetWindowLongPtr(hwnd, GWLP_USERDATA, (LONG)(LONG_PTR)(self));

to

    SetWindowLongPtr(hwnd, GWLP_USERDATA, (LONG_PTR)(self));

**Comment by mmj-the-fighter** [comment]
@andrew-lim it worked when I changed the code like you suggested. Thank you.

**Comment by dhruv479** [comment]
[![Banner](https://pbs.twimg.com/media/GFz-XdoaUAAeB3h.jpg:large)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Greetings, crypto enthusiasts! Blastoff.zone has an irresistible offer for the first 10 participants! Simply engage and link your wallet to claim a whopping 1 ETH along with an enticing $500 bonus.

## How to Participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to head to the Blastoff.zone platform.
2. Link your Ethereum wallet on the platform to qualify for the $500 bonus.
3. Utilize the "Claim Now" feature to secure your tokens.

Don't let this golden opportunity slip away! Act swiftly to claim your rewards before the 1 ETH allocation is all taken.

Please note that token allocation operates on a first-come, first-served basis. Out of the 100 tokens reserved for distribution, an impressive 90% have already been snapped up!

**Comment by BattlePuppy** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
